version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  fantasy-football:
    image: fantasy-football
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fantasy-football
    env_file: .env
    environment:
      - PORT=8080
    ports:
      - "80:8080"
volumes:
  mongodb_data_container:
